export const SWITCH_TO_LIGHT_MODE = 'SWITCH_TO_LIGHT_MODE';
export const SWITCH_TO_DARK_MODE = 'SWITCH_TO_DARK_MODE';

export const TEMPERATURE_IN_CELSIUS = 'TEMPERATURE_IN_CELSIUS';
export const TEMPERATURE_IN_FAHRENHEIT = 'TEMPERATURE_IN_FAHRENHEIT';